sudo: required
os: linux
language: c
compiler: clang
env:
- secure: "vmVFv4ccRBy9TyLh4Me95PKrG/1ttuKuQaC6E0l/ALhxIwQ2PrESwcO4TSiZemPjP6R70NaKQLpyNvaLGlNdQmamooNCsLDTc3vKpgXqLHfIExns6Uv4a5p/1HK7ADgJfNesRL9LRUhxWm2KQ+MqXFi79rGt7xGVdUK5hGTt9IZpq/hwBPyyKafdAjBeWW7Yoy99/WleTenot30XDEa3ErcUIBego6mWREwWLJCGyvTDyJOpLGDBDl9X2r3wQOoU1FwC2BXpZb1/XyqFK5mTTOrnwzf+OU3p5gDOVlXzKMkT6KxpQ94O8O2QrBJ4jPwoa5gExu8NrItXxCkACb6cKxcHSCKAgzfs/6Qw2cRYLdqti3aHWVA7IPAaPLH/JqwNqNLT4BZ3qIvlMYkyI3Pp3I+YiYeVyzWQ762sz+BWozWbL+9+osjC1DsW/wOygqPqFcL7H4eDxnVRUVRfTcrT3b2Pzt6DWyZVks93qt7ZNf35sob1UvHr2cNgUQSoVpgqcWZ2KhDj00aT9X62nziGuJC8SFVqTUiJsionlsK8HM7aQoqSQ+pA7ZVxs8XTJzGxcuputI7fbNfg6EXUL6maXBJHHeejNBhf8dYQblGZqU+eTFUjM5upvpu337bNBOQLu1u2oU+pZxtZtRjcV36AbMs0rWUrZEFHJZROWYdXicI="

notifications:
  email: false

before_install:
    - sudo apt-get install sshpass
    - echo "|1|319gPn4gbuUnAOPWNsRR1+PX6i0=|lrV+WR6nMUM7/hgPHEBzzDDogmI= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8Z6HD2zR2C45TVnpAx8BaV96pK5RmITKCfl3yYxkTxrryLo8rhz/N6CPK1MgRv1iChZh7d1rrarLzMAcZq+B6pB5k1aieoOIIz3WpeWrRImcAK/D3ltN4gq4Uaccah48ojjD3o9MBTPqgM2tMyVdYRfwIlcMVH3tXoFax8/ISADkA6ZcoJcFCCriJmUVmLM/vypPXQPEnskxO3EepQCKvAtjFA0W4qoIyH7vV852HS8fLwRSI3YZfxcWmunqFo0fSnw97powGJxSN85SG2AQGib1aS9Tv/s52vDfW/0PHg04FMtPqDOBPn1fQi37ygFzWeWXetNhg6a9VTz94pgVJ" >> ~/.ssh/known_hosts
    - ./bootstrap-vitasdk.sh
    - export VITASDK=/usr/local/vitasdk
    - export PATH=$VITASDK/bin:$PATH
    - cp config.travis config

script:
    - ./vdpm -i zlib
    - ./vdpm -i libpng
    - ./vdpm -i libexif
    - ./vdpm -i libjpeg
    - ./vdpm -i jansson
    - ./vdpm -i sqlite
    - ./vdpm -i fftw
    - ./vdpm -i libvita2d
    - ./vdpm -i libmad
    - ./vdpm -i libogg
    - ./vdpm -i libvorbis
